type User {
  id: String
  email: String
  username: String
}

type Query {
  listUsers: [User]
  getUserById(id: String!): User
}

type AuthResp {
  token: String
  info: User
}

type Mutation {
  createUser(email: String!, username: String!, password: String!): AuthResp
}
