type User {
  id: String
  email: String
  username: String
}

type AuthResp {
  token: String
  info: User
}

type Query {
  getUserById(id: String!): User
  login(email: String!, password: String!): AuthResp
}

type Mutation {
  createUser(email: String!, username: String!, password: String!): AuthResp
  deleteAccount: Boolean
}
